server:
  port: 6666
spring:
  datasource:
    generate-unique-name: false
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/word_remember_helper?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1qaz!QAZ
    hikari:
      pool-name: DateHikariCp
      minimum-idle: 10
      idle-timeout: 180000
      maximum-pool-size: 60
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true